order_high: [1, 1, 1]
order_low: [0, 0, 0]
fourier_orders: [0,1]
mean_orders: [0,3]
exog_steps: [0,1]
decompose: [0,1]
n_estimators: [0]
max_depth: [None]
estimator: ["linear"]
learning_rate: [0]
interaction: [0]