order_high: [1, 1, 1]
order_low: [0, 0, 0]
fourier_orders: [0]
mean_orders: [0, 7]
exog_steps: [0, 1, 2]
decompose: [0,1]
n_estimators: [50, 250]
max_depth: [None, 3,7]
estimator: ["dt", "linear"]
learning_rate: [1.0,0.1]
interaction: [0,1,2]