defaults:
  - search: 0_full_search.yaml

model_type: "sarimax" # model type that is evaluated
loc: "Moehne" # location
dir: "lot" # direction of the PS monitoring or "lot" for the pendulum swing
forecast_path: "../save_and_results/igarss_models/"
save_path: "../save_and_results/igarss_new/"
criteria: "MSE" # model selection criteria
parallel: False   # Does Multiprocessing
remove_W: False # Runs all specifications but completely removes W
remove_T: False # Runs all specifications but completely removes T
remove_everything: False # Used for baseline forecasts to only keep the actual 4 baseline models.


source_path: "../raw_data/"
cache_path: "../save_and_results"
all_locs: ["Moehne", "Fuerwigge", "Verse", "Lister", "Bigge", "Sorpe"]  # These are all available models
all_dirs: ["asc0", "ew", "ver", "desc0"] #  "asc1", "desc1" # Directions (not all are available everywhere)
all_model_types: ["linear", "sarimax", "forest", "ada"] # run var seperate as it crashes the lot (just one var) model types that are available